name: swagger_parser_pages
description: Web interface for Development Kit
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.3.7
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  swagger_parser:
    path:
      ../swagger_parser
  url_launcher: ^6.1.11
  dio: ^5.3.2
  highlight: ^0.7.0
  code_text_field: ^1.1.0
  flutter_highlight: ^0.7.0
  group_button: ^5.3.2
  auto_route: ^5.0.4
  rive: ^0.11.14
  flutter_bloc: ^8.1.3
  freezed: ^2.4.2


dependency_overrides:
  analyzer: ^5.0.0


dev_dependencies:
  carapacik_lints: ^1.4.0
  build_runner: ^2.3.3
  auto_route_generator: ^5.0.3
#    git:
#      url: https://gitlab.tools.kibkw.digital/mobile/common/auto_route_library.git
#      ref: main
#      path: auto_route_generator

flutter:
  uses-material-design: true

  assets:
    - assets/
